# Copyright (C) 2021 The uOFW team
# See the file COPYING for copying permission.

TARGET = usbacc
OBJS = usbacc.o

#DEBUG = 1

LIBS = -lsceUsbBus_driver -lInterruptManagerForKernel -lThreadManForKernel -lUtilsForKernel

include ../../lib/build.mak
