# Copyright (C) 2011, 2012 The uOFW team
# See the file COPYING for copying permission.

TARGET = usersystemlib
OBJS = kernel_library.o intr.o

#DEBUG = 1

LIBS = -lSysMemUserForUser -lInterruptManager -lThreadManForUser

include ../../lib/build.mak
