# Copyright (C) 2011, 2012, 2013, 2014, 2015 The uOFW team
# See the file COPYING for copying permission.

TARGET = rtc
OBJS = rtc.o

LIBS = -lInitForKernel -lInterruptManagerForKernel -lKDebugForKernel -lSysMemForKernel -lSysclibForKernel \
	   -lThreadManForKernel -lUtilsForKernel -lsceSuspendForKernel -lsceSysEventForKernel -lsceSyscon_driver

include ../../lib/build.mak
