# Copyright (C) 2016 The uOFW team
# See the file COPYING for copying permission.

TARGET = threadman
OBJS = threadman.o

#DEBUG = 1

LIBS = 	-lInterruptManagerForKernel -lExceptionManagerForKernel -lSysMemForKernel -lKDebugForKernel \
		-lsceSuspendForKernel -lSysclibForKernel -lLoadCoreForKernel

include ../../lib/build.mak
