# Copyright (C) 2011, 2012 The uOFW team
# See the file COPYING for copying permission.

TARGET = interruptman
OBJS = start.o interruptman.o end.o imports.o

PRX_EXPORTS=exports.exp

include ../../lib/build.mak

