# Copyright (C) 2011, 2012 The uOFW team
# See the file COPYING for copying permission.

TARGET = interruptman
OBJS = start.o interruptman.o end.o

#DEBUG = 1

LIBS = -lExceptionManagerForKernel -lLoadCoreForKernel -lSysMemForKernel -lsceSuspendForKernel

include ../../lib/build.mak

