# Copyright (C) 2011, 2012, 2013, 2014 The uOFW team
# See the file COPYING for copying permission.

TARGET = http_storage
OBJS = http_storage.o

#DEBUG = 1

LIBS = -lSysMemForKernel -lSysclibForKernel -lIoFileMgrForKernel -lModuleMgrForKernel -lsceChkreg_driver

include $(ROOT_DIR)/lib/build.mak