# Copyright (C) 2011, 2012 The uOFW team
# See the file COPYING for copying permission.

TARGET = codec
OBJS = codec.o

LIBS = -lThreadManForKernel -lsceSysEventForKernel -lsceI2c_driver -lsceSysreg_driver -lsceGpio_driver

include ../../lib/build.mak

