# Copyright (C) 2011, 2012 The uOFW team
# See the file COPYING for copying permission.

TARGET = iofilemgr
OBJS = stdio.o iofilemgr.o

DEBUG = 1

LIBS = -lThreadManForKernel -lSysclibForKernel -lSysMemForKernel -lKDebugForKernel -lInterruptManagerForKernel -lsceSuspendForKernel

include $(ROOT_DIR)/lib/build.mak

