# Copyright (C) 2011, 2012 The uOFW team
# See the file COPYING for copying permission.

TARGET = led
OBJS = led.o

LIBS = -lSysMemForKernel -lsceSuspendForKernel -lsceSysEventForKernel -lSysclibForKernel -lsceSyscon_driver \
       -lsceGpio_driver -lInterruptManager
       

include ../../lib/build.mak

