# Copyright (C) 2011, 2012 The uOFW team
# See the file COPYING for copying permission.

TARGET = mlnbridge_msapp
OBJS = mlnbridge_msapp.o

LIBS = -lModuleMgrForKernel -lSysclibForKernel -lSysMemForKernel -lsceRtc_driver -lsceReg_driver -lsceDve_driver  

include ../../lib/build.mak