# Copyright (C) 2011, 2012 The uOFW team
# See the file COPYING for copying permission.

TARGET = syscon
OBJS = power.o syscon.o

LIBS = -lsceSysEventForKernel -lKDebugForKernel -lInterruptManagerForKernel -lThreadManForKernel -lSysclibForKernel -lUtilsForKernel -lsceSysreg_driver -lsceGpio_driver

include $(ROOT_DIR)/lib/build.mak

