# Copyright (C) 2011, 2012 The uOFW team
# See the file COPYING for copying permission.

TARGET = usersystemlib
OBJS = usersystemlib.o intr.o lazy.o thread.o lwmutex.o mem.o

#DEBUG = 1

LIBS = -lSysMemUserForUser -lInterruptManager -lThreadManForUser

include $(ROOT_DIR)/lib/build.mak
