# Copyright (C) 2011, 2012 The uOFW team
# See the file COPYING for copying permission.

TARGET = ge
OBJS = stall.o ge.o

LIBS = -lInterruptManagerForKernel -lThreadManForKernel -lsceSysreg_driver -lKDebugForKernel -lUtilsForKernel -lsceSysEventForKernel -lSysMemForKernel -lSysclibForKernel

include ../../lib/build.mak

