# Copyright (C) 2011, 2012, 2013, 2014 The uOFW team
# See the file COPYING for copying permission.

TARGET = http_storage
OBJS = http_storage.o

#DEBUG = 1

LIBS = -lIoFileMgrForKernel -lModuleMgrForKernel -lSysMemForKernel -lSysclibForKernel -lsceChkreg_driver

include ../../lib/build.mak