# Copyright (C) 2011, 2012, 2013, 2014 The uOFW team
# See the file COPYING for copying permission.

TARGET = http_storage
OBJS = http_storage.o k1set.o imports.o exports.o

#DEBUG = 1

LIBS = -lIoFileMgrForKernel -lModuleMgrForKernel -lSysMemForKernel

include ../../lib/build.mak