# Copyright (C) 2011, 2012 The uOFW team
# See the file COPYING for copying permission.

TARGET = ge
OBJS = stall.o ge.o

DEBUG = 0

LIBS = -lInterruptManagerForKernel -lThreadManForKernel -lsceSysreg_driver -lKDebugForKernel -lUtilsForKernel -lsceSysEventForKernel -lSysMemForKernel -lSysclibForKernel -lInitForKernel

include $(ROOT_DIR)/lib/build.mak

