# Copyright (C) 2011, 2012 The uOFW team
# See the file COPYING for copying permission.

TARGET = sysmem
OBJS = start.o debug.o sysevent.o suspend.o assert.o sysclib.o utils.o kdebug.o main.o

PRX_EXPORTS=exports.exp

include ../../lib/build.mak

