# Copyright (C) 2011, 2012 The uOFW team
# See the file COPYING for copying permission.

TARGET = sysmem
OBJS = start.o heap.o partition.o memory.o misc.o debug.o memoryop.o uid.o sysevent.o suspend.o assert.o memblock.o sysclib.o utils.o kdebug.o sysmem.o intr.o

include ../../lib/build.mak

