# Copyright (C) 2011, 2012, 2013, 2014 The uOFW team
# See the file COPYING for copying permission.

TARGET = mediaman
OBJS = mediaman.o

LIBS = -lInterruptManagerForKernel -lIoFileMgrForKernel -lSysclibForKernel -lSysMemForKernel \
       -lThreadManForKernel

include $(ROOT_DIR)/lib/build.mak