# Copyright (C) 2011, 2012 The uOFW team
# See the file COPYING for copying permission.

TARGET = chnnlsv
OBJS = chnnlsv.o exports.o imports.o

#DEBUG = 1

LIBS = -lThreadManForKernel

include ../../lib/build.mak
