# Copyright (C) 2011, 2012 The uOFW team
# See the file COPYING for copying permission.

TARGET = chnnlsv
OBJS = chnnlsv.o

#DEBUG = 1

LIBS = -lThreadManForKernel -lpspsemaphore

include ../../lib/build.mak
