# Copyright (C) 2011, 2012, 2013, 2014 The uOFW team
# See the file COPYING for copying permission.

TARGET = np_inst
OBJS = np_inst.o k1set.o

#DEBUG = 1

LIBS = -lThreadManForKernel -lSysclibForKernel -lIoFileMgrForKernel -lscePspNpDrm_driver -lscePcact_driver -lsceRtc_driver -lsceOpenPSID_driver

include ../../lib/build.mak