# Copyright (C) 2011, 2012, 2013 The uOFW team
# See the file COPYING for copying permission.

TARGET = libaac
OBJS = libaac.o

#DEBUG = 1

LIBS = -lKernel_Library -lThreadManForUser -lsceAudiocodec

include ../../lib/build.mak
