# Copyright (C) 2011, 2012, 2013 The uOFW team
# See the file COPYING for copying permission.

TARGET = libaac
OBJS = libaac

#DEBUG = 1

LIBS = -lKernel_Library -lThreadManForUser -lsceAudioCodec

include ../../lib/build.mak
