# Copyright (C) 2011, 2012 The uOFW team
# See the file COPYING for copying permission.

TARGET = me_wrapper
OBJS = init.o me_wrapper.o

LIBS = -lsceSysreg_driver -lUtilsForKernel -lIoFileMgrForKernel -lsceSysEventForKernel -lSysclibForKernel -lSysMemForKernel -lInterruptManagerForKernel -lThreadManForKernel -lsceDdr_driver -lsceSyscon_driver -lsceLFatFs_driver -lsceWmd_driver

include $(ROOT_DIR)/lib/build.mak

