# Copyright (C) 2024 The uOFW team
# See the file COPYING for copying permission.

TARGET = libparse_http
OBJS = libparse_http.o

#DEBUG = 1

LIBS = -lKernel_Library -lThreadManForUser

include $(ROOT_DIR)/lib/build.mak
