# Copyright (C) 2011, 2012 The uOFW team
# See the file COPYING for copying permission.

TARGET = audio
OBJS = audio.o

DEBUG = 1

LIBS = -lsceCodec_driver -lInterruptManagerForKernel -lSysclibForKernel -lThreadManForKernel -lsceSysEventForKernel -lSysMemForKernel -lDmacManForKernel -lsceDdr_driver -lsceSysreg_driver -lsceClockgen_driver -lUtilsForKernel

include ../../lib/build.mak

