# Copyright (C) 2011, 2012 The uOFW team
# See the file COPYING for copying permission.

TARGET = libatrac3plus
OBJS = libatrac3plus.o

#DEBUG = 1

LIBS = -lKernel_Library -lsceAudiocodec

include ../../lib/build.mak

