# Copyright (C) 2011, 2012, 2013 The uOFW team
# See the file COPYING for copying permission.

TARGET = clockgen
OBJS = clockgen.o

#DEBUG = 1

LIBS = -lThreadManForUser -lsceSysEventForKernel -lsceI2c_driver

include $(ROOT_DIR)/lib/build.mak
