# Copyright (C) 2011, 2012 The uOFW team
# See the file COPYING for copying permission.

TARGET = systimer
OBJS = systimer.o

LIBS = -lInterruptManager -lInterruptManagerForKernel -lsceSuspendForKernel

include $(ROOT_DIR)/lib/build.mak

