# Copyright (C) 2011, 2012 The uOFW team
# See the file COPYING for copying permission.

TARGET = ctrl
OBJS = ctrl.o

LIBS = -lSysMemForKernel -lsceSuspendForKernel -lsceSysEventForKernel -lKDebugForKernel -lInterruptManagerForKernel -lSysclibForKernel -lThreadManForKernel -lSysTimerForKernel -lInitForKernel -lsceDisplay_driver -lsceSyscon_driver

PRX_EXPORTS = exports.exp

include ../../lib/build.mak

