# Copyright (C) 2021 The uOFW team
# See the file COPYING for copying permission.

TARGET = chkreg
OBJS = chkreg.o

#DEBUG = 1

LIBS = -lsceIdStorage_driver -lThreadManForKernel -lpspsemaphore

include ../../lib/build.mak
