#define BadVaddr $8
#define Count    $9
#define Compare  $11
#define Status   $12
#define Cause    $13
#define EPC      $14
#define PrID     $15
#define Config   $16
#define EBase    $25
#define TagLo    $28
#define TagHi    $29
#define ErrorPC  $30

#define VFPU_PFXS $128
#define VFPU_PFXT $129
#define VFPU_PFXD $130
#define VFPU_CC   $131
#define VFPU_INF4 $132
#define VFPU_REV  $135
#define VFPU_RCX0 $136
#define VFPU_RCX1 $137
#define VFPU_RCX2 $138
#define VFPU_RCX3 $139
#define VFPU_RCX4 $140
#define VFPU_RCX5 $141
#define VFPU_RCX6 $142
#define VFPU_RCX7 $143

#define zr 0

.set noat
.set noreorder

