# Copyright (C) 2011, 2012 The uOFW team
# See the file COPYING for copying permission.

TARGET = isofs
OBJS = isofs.o

DEBUG = 0
INSTALLER = 1

LIBS = -lInterruptManagerForKernel -lSysMemForKernel -lSysclibForKernel -lThreadManForKernel \
       -lIoFileMgrForKernel -lsceRtc_driver -lsceUmd -lsceUmdMan_driver

include $(ROOT_DIR)/lib/build.mak
