# Copyright (C) 2011, 2012, 2013 The uOFW team
# See the file COPYING for copying permission.

TARGET = wlanfirm_02g
OBJS = wlanfirm.o

#DEBUG = 1

LIBS = -lsceIdStorage_driver -lsceWlanDrv_driver

include $(ROOT_DIR)/lib/build.mak
