# Copyright (C) The uOFW team
# See the file COPYING for copying permission.

TARGET = chkreg
OBJS = chkreg.o

LIBS = -lsceIdStorage_driver -lThreadManForKernel -lpspsemaphore

include ../../lib/build.mak
