# Copyright (C) 2011, 2012, 2013, 2014 The uOFW team
# See the file COPYING for copying permission.

TARGET = np_core
OBJS = np_core.o

#DEBUG = 1

LIBS = -lSysMemForKernel -lSysclibForKernel -lsceOpenPSID_driver

include $(ROOT_DIR)/lib/build.mak