# Copyright (C) 2011, 2012 The uOFW team
# See the file COPYING for copying permission.

TARGET = exceptionman
OBJS = excep.o exceptions.o intr.o nmi.o

PRX_EXPORTS=exports.exp

include ../../lib/build.mak

